name: 'Reusable MAIN'

on:
  workflow_call:
    inputs:
      token:
        description: 'Token de autenticação'
        type: string
        required: true
      name:
        description: 'Nome'
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ECHO
        run: |
          echo Main Workflow called
          echo " ${{ inputs.name }} "
          echo " ${{ inputs.token }} "

      # Adicione outras etapas relevantes para o seu fluxo de trabalho secundário
      # Por exemplo, construir, testar, implantar, etc.
